### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [okbob/ncurses-st-menu#1]
I would like to point out that an identifier like “[`_ST_MENU_ITEM`](https://github.com/okbob/ncurses-st-menu/blob/1dde023a2ecc65bcfeaa145734008a58d42e0ff3/include/st_menu.h#L60 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by okbob** [comment]
This name is based on conventions used by ncurses library. So maybe is not correct against SEI CERT C Coding Standard, but it is ok (for me) because use same conventions like library that should to enhance.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by okbob** [comment]
pá 13. 9. 2019 v 7:53 odesílatel Markus Elfring <notifications@github.com>
napsal:

> How do you think about to avoid that this software depends on undefined
> behaviour
> <https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106>
> ?
>
use common sense, please. The same naming convention is used in ncurses -
https://en.wikipedia.org/wiki/Ncurses

Sometimes you should to choose between two conventions. But use any naming
convention cannot to break anything.

**Comment by okbob** [comment]
> How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106)?

I rechecked it - and this name is absolutely correct - this is a false alarm

**Comment by elfring** [comment]
More software components were published which are still standard incompliant.

**Comment by okbob** [comment]
pá 13. 9. 2019 v 8:06 odesílatel Markus Elfring <notifications@github.com>
napsal:

> More software components were published which are still standard
> incompliant.
>
For me, in this, area only ANSI C is a standard.
https://en.wikipedia.org/wiki/ANSI_C . Others are  recommendations.

And when you will write a library, the library should be consistent in
environment where it is used. So I wrote a library based on ncurses and it
is consistent with ncurses.

**Comment by elfring** [comment]
I find [standard compliance](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") more important for source files of the involved programming languages than a questionable consistency.

**Comment by okbob** [comment]
I don't think so I break any rules when I use _ST_XXXX as identifier inside library.  Can be different, if I used it in application.

**Comment by elfring** [comment]
>I don't think so I break any rules when I use _ST_XXXX as identifier inside library.

* Does this identifier belong to the implementation of a compiler for the programming language “C” (or “C++”)?
* Do you care for achieving more defined software behaviour?

**Comment by okbob** [comment]
pá 13. 9. 2019 v 9:00 odesílatel Markus Elfring <notifications@github.com>
napsal:

**Comment by elfring** [comment]
I suggest to reduce the tampering with the reserved name space also for your software.

**Comment by okbob** [comment]
fixed by latest commit

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/okbob/ncurses-st-menu/commit/a97310fc22b7373860371ca596f1ffc22b7be028 "Renaming of an identifier").
