### ISSUE TITLE
Selections not working from mouse

### ISSUE THREAD

**Issue by tysenmoore-xse** [okbob/ncurses-st-menu#11]
If I change the demo.c (for example) to to not block waiting for an input event the menu does not work correctly.  I added the following to the main()

```
nodelay(stdscr, TRUE);
```
I can no longer get selections while using the mouse.  For example, go into the menu and select something, it does not work.  If I use the command bar key presses they work.  I also noticed the submenus open just fine.  The selection of any item using the mouse seems to be the only problem.

I also tried to step through the code and it sometimes works.

Is this expected behavior? (I assume no) Has anyone experienced this before?  Is this mode supported by the menu? Or, am I not using this feature properly?

Thanks for the time and any support.

**Comment by okbob** [comment]
pá 13. 3. 2020 v 21:05 odesílatel Tysen Moore <notifications@github.com>
napsal:

> If I change the demo.c (for example) to to not block waiting for an input
> event the menu does not work correctly. I added the following to the main()
>
> nodelay(stdscr, TRUE);
>
>
yes, in this case doesn't work correctly my implementation of mouse-click.
Menu activation requires mouse click - but for my application I had to
implemented it by self - from button-press and button-released events.

Probably with nodelay some other events is coming to driver and breaks the
expected sequence


 I can no longer get selections while using the mouse. For example, go into
> the menu and select something, it does not work. If I use the command bar
> key presses they work. I also noticed the submenus open just fine. The
> selection of any item using the mouse seems to be the only problem.
>
the working part is based on only one event button1-press


> I also tried to step through the code and it sometimes works.
>
> Is this expected behavior? (I assume no) Has anyone experienced this
> before? Is this mode supported by the menu? Or, am I not using this feature
> properly?
>
Unfortunately it is expected behave - in this state. Generally the mouse
support is not too good, and the demoapp is not written for nodelay(stdscr,
TRUE). You should to wait somewhere else your CPU fill fire. More, you
should to filter ERR events before pushing this event to st menu driver.

**Comment by okbob** [comment]
I did a test and the problem is in ERR value. When no key is pressed, then `get_event` returns `ERR` value. This value should not be send to `st_menu_driver` function. So if you use

<pre>
        c = get_event(&mevent, &alt);
    
        if (c != ERR) /* add this test */
            processed = st_menu_driver(menu, c, alt, &mevent);
        doupdate();
</pre>

Then st-menu will work for you. Attention without a waiting somewhere, then `nodelay(stdscr, TRUE);` does very high CPU utilization.

**Comment by tysenmoore-xse** [comment]
Thanks so much for the help.  This did fix my problem.
