### ISSUE TITLE
NetBSD failure to build

### ISSUE THREAD

**Issue by ghost** [okbob/ncurses-st-menu#12]
I'm having an issue setting this up on NetBSD.  I first get an error with ./autogen.sh
![autogensh](https://user-images.githubusercontent.com/71466591/94366222-afdc0280-00a4-11eb-95ef-ec78b07702f0.png)

Then doing the command again appears to work for some reason
![autogenshfixed](https://user-images.githubusercontent.com/71466591/94366227-bb2f2e00-00a4-11eb-996e-a8824b905d6f.png)

And then running ./configure tells me that netbsd isn't supported despite the documentation stating it does
![configurefailed](https://user-images.githubusercontent.com/71466591/94366235-cb470d80-00a4-11eb-8d1e-f83abacc9b09.png)

Is there a dependency I'm missing?

Edit: I just wanted to add I get the same exact errors in OpenBSD too. So this appears to be a *BSD issue rather than a specific OS issue.

Edit 2:  autogen.sh also fails on linux, but regular configure and make works without issue.

**Comment by okbob** [comment]
https://github.com/braice/MuMuDVB/issues/189

please try to install gettext

ne 27. 9. 2020 v 15:36 odesílatel notepade <notifications@github.com>
napsal:

**Comment by ghost** [comment]
I installed gettext on NetBSD and ./autogen.sh worked. I have no idea what it did, but it worked. Problem is that doing ./configure still says that x86_64-unknown-netbsd9.0 is not supported. That didn't change at all. What should I do now?

**Comment by okbob** [comment]
ne 27. 9. 2020 v 20:03 odesílatel notepade <notifications@github.com>
napsal:

> I installed gettext on NetBSD and ./autogen.sh worked. I have no idea what
> it did, but it worked. Problem is that doing ./configure still says that
> x86_64-unknown-netbsd9.0 is not supported. That didn't change at all. What
> should I do now?
>
It is gcc error probably - what is version of your gcc compiler?

https://stackoverflow.com/questions/56814847/error-installing-gcc-3-0-1-for-x86-64-architecture

can you send config.log?

**Comment by ghost** [comment]
Here is the config.log
https://bpa.st/JPKA
Also, NetBSD 9.0 is using gcc 7.

**Comment by okbob** [comment]
ne 27. 9. 2020 v 20:31 odesílatel notepade <notifications@github.com>
napsal:

> Here is the config.log
> https://bpa.st/JPKA
> Also, NetBSD 9.0 is using gcc 7.
>

I found on internet - you should to run

autoreconf --install

and maybe you should to install libtool

This problem is related to your build environment, maybe gcc is too old or
some component

**Comment by ghost** [comment]
Can I please have a minimal required versions for autoconf, automake, make, and every other tool you used? I think netbsd using ancient packages might be the issue here. For example, automake from pkgbuilds is 1.16, [edit: 1.16.2 isn't ancient like I previous thought it was.] I wouldn't mind having to manually install the tools, but I need to know what minimal versions to use.

**Comment by okbob** [comment]
ne 27. 9. 2020 v 22:41 odesílatel notepade <notifications@github.com>
napsal:

> Can I please have a minimal required versions for autoconf, automake,
> make, and every other tool you used? I think netbsd using ancient packages
> might be the issue here. For example, automake from pkgbuilds is 1.16,
> which is ancient. I wouldn't mind having to manually install the tools, but
> I need to know what minimal versions to use.
>
It is a hard task - I use Fedora, which uses very fresh tools. I know so
pspg is working on MacOS, that uses older versions. I didn't actualize
these scripts 2 years ago, so two years, three years old environment should
work. It was compileable on RH 6, that is from 2010. I am sorry - I have no
more ideas - and I never used BSD systems, so I have no knowledge about
that.

**Comment by okbob** [comment]
po 28. 9. 2020 v 7:46 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> ne 27. 9. 2020 v 22:41 odesílatel notepade <notifications@github.com>
> napsal:
>
>> Can I please have a minimal required versions for autoconf, automake,
>> make, and every other tool you used? I think netbsd using ancient packages
>> might be the issue here. For example, automake from pkgbuilds is 1.16,
>> which is ancient. I wouldn't mind having to manually install the tools, but
>> I need to know what minimal versions to use.
>>
> It is a hard task - I use Fedora, which uses very fresh tools. I know so
> pspg is working on MacOS, that uses older versions. I didn't actualize
> these scripts 2 years ago, so two years, three years old environment should
> work. It was compileable on RH 6, that is from 2010. I am sorry - I have no
> more ideas - and I never used BSD systems, so I have no knowledge about
> that.
>

please, if you do some research, send me info about it. It can be
interesting for other people.

**Comment by okbob** [comment]
any progress?
