### ISSUE TITLE
SDL2 support?

### ISSUE THREAD

**Issue by IdoitEngineer** [okbob/ncurses-st-menu#13]
The readme suggests that X11/WinCon are the only options when using PDCurses.
Does st-menu support PDCurses + SDL2 ?

**Comment by okbob** [comment]
Hi

pá 30. 7. 2021 v 4:38 odesílatel The Idiot Engineer <
***@***.***> napsal:

> The readme suggests that X11/WinCon are the only options when using
> PDCurses.
> Does st-menu support PDCurses + SDL2 ?
>
I have no idea. But I don't see any reasons why not. ncurses-st-menu
doesn't do any extra operations. Nobody reported some issues, but nobody
reported success too (from this platform).

Regards

Pavel
