### ISSUE TITLE
got errors building on termux

### ISSUE THREAD

**Issue by cargilcm** [okbob/ncurses-st-menu#14]
Hello, I've not found any project like yours where there are sub menus in a character cell display(ncurses codebase).  I've run into some problems compiling and wondered if you might help me  

**To compile I ran**:
`gcc -I./include ~/ncurses-st-menu/ncmenu.c`
where nmenu.c consist of the contents under "usage" and got:

**Error#1**

**`error: incompatible pointer to integer conversion initializing 'char' with an expression of type 'ST_MENU_ITEM[2]' (aka 'struct st_ST_MENU_ITEM[2]') [-Wint-conversion]`**
 

Line 76  `|       {"~F~ile", 61, NULL, 0, _file},`

The compiler indicates __file variable for the call complained about above.
   

  
_And_

**Error#2** 

**`error: call to undeclared function 'st_menu_set_desktop_panel'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]`**

 Line 134 `|         st_menu_set_desktop_panel(mainpanel);`
  
  Thanks very much for your project which even nicely adds screenshots; thanks in advance for your help.

**Comment by okbob** [comment]
looks so your code is missing `st_menu.h` include file.

`st_menu_set_desktop_panel` is wrong. Correct name is `st_menu_set_desktop_window`.

Can you compile demo applications from `demo` directory?

just

    ./configure
    make

**Comment by cargilcm** [comment]
Great question/tip/reiterating what was previously explained. There's something peculiar about the termux autoconf related to ar-lib.

I can't build in termux by default. But when I drop into a proot-distro that emulates a proper alpine Linux distro inside of termux I can build and run the demos! 

Being that the complaint is:  `configure: error: cannot find required auxiliary files: ar-lib` I know I prob need to let the termux developers know but I'm case you're curious I also found this post which.. Could shed some light?! [Can't compile with ar-lib](https://bbs.archlinux.org/viewtopic.php?pid=1572137#p1572137) I just don't know enough about autoconf/c language to know if this is helpful. 

I note specifically where the user states something may be linked to the old ncurses library. Let me know if you have witnessed anything like this before or can point me to the right direction please. Thank you Mr.Stehule

**Comment by okbob** [comment]
pá 18. 10. 2024 v 15:05 odesílatel Chris Cargile ***@***.***>
napsal:

> Great question/tip/reiterating what was previously explained. There's
> something peculiar about the termux autoconf related to ar-lib.
>
> I can't build in termux by default. But when I drop into a proot-distro
> that emulates a proper alpine Linux distro inside of termux I can build and
> run the demos!
>
> Being that the complaint is: configure: error: cannot find required
> auxiliary files: ar-lib I know I prob need to let the termux developers
> know but I'm case you're curious I also found this post which.. Could shed
> some light?! Can't compile with ar-lib
> <https://bbs.archlinux.org/viewtopic.php?pid=1572137#p1572137> I just
> don't know enough about autoconf/c language to know if this is helpful.
>
> I note specifically where the user states something may be linked to the
> old ncurses library. Let me know if you have witnessed anything like this
> before or can point me to the right direction please. Thank you Mr.Stehule
>
I am sorry, this is first time so I can see the name "ar-lib"

I found https://bugs.gentoo.org/775968

there was some issue in Automake - fixed

3676 2020-11-14  Jim Meyering  ***@***.***> 3677  3678 	tests:
avoid failures due to missing ar-lib 3679  3680 	* t/ar4.sh: Create
dummy ar-lib, as done in other tests, 3681 	to avoid failure like
this: 3682 	configure: error: cannot find required auxiliary files:
ar-lib 3683 	* t/ar5.sh: Likewise.


ncurses-st-menu has just one prerequisite - ncurses or pdcurses library
(and clib).

**Comment by cargilcm** [comment]
`pkg install binutils-is-llvm` solves the ar-lib issue that building with autoconf/termux complains of.  

Cool. Also a small correction: there's a typo on the readme under building for curses the text _LD_LIBRARY_PATH=. /.demoapp_sl_  should read LD_LIBRARY_PATH=. **./**demoapp_sl   (the path to demoapp_sl should be revised to a period before slash).

Thanks!

**Comment by okbob** [comment]
ne 29. 12. 2024 v 23:28 odesílatel Chris Cargile ***@***.***>
napsal:

> pkg install binutils-is-llvm solves the ar-lib issue that building with
> autoconf/termux complains of.
>
> Cool. Also a small correction: there's a typo on the readme under building
> for curses the text *LD_LIBRARY_PATH=. /.demoapp_sl* should read
> LD_LIBRARY_PATH=. **./**demoapp_sl (the path to demoapp_sl should be
> revised to a period before slash).
>
fixed

thank you for info


Thanks!
