### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [okbob/ncurses-st-menu#2]
[Extra null pointer checks are not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [_st_menu_free](https://github.com/okbob/ncurses-st-menu/blob/a4ad25e2ad67375f29be47070a58bf156cd419ee/src/st_menu.c#L2131 "_st_menu_free function")
- [st_cmdbar_free](https://github.com/okbob/ncurses-st-menu/blob/a4ad25e2ad67375f29be47070a58bf156cd419ee/src/st_menu.c#L2727 "st_cmdbar_free function")

**Comment by okbob** [comment]
I use this technique in conformance with PostgreSQL community. So I don't see this as issue.

**Comment by elfring** [comment]
I suggest to [take the current POSIX standard into account](https://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for null before free(p)?") for corresponding software adjustments.
Will another small source code reduction be nicer here?

**Comment by okbob** [comment]
pá 13. 9. 2019 v 12:30 odesílatel Markus Elfring <notifications@github.com>
napsal:

> I suggest to take the current POSIX standard into account
> <https://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html>
> for corresponding software adjustments.
> Will another small source code reduction be nicer here?
>
maybe on computers with 10kB memory. It's few bytes.
