### ISSUE TITLE
compiling demo

### ISSUE THREAD

**Issue by atakito** [okbob/ncurses-st-menu#3]
Hello 
I have an error compiling demo
demo/demo.c: In function ‘get_event’:
demo/demo.c:57:2: error: unknown type name ‘wint_t’
  wint_t ch;
  ^~~~~~
demo/demo.c:68:8: warning: implicit declaration of function ‘get_wch’ [-Wimplicit-function-declaration]
  ret = get_wch(&ch);
        ^~~~~~~
Makefile:35: recipe for target 'demoapp' failed

gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

I'm a newbie in C
thanks in advance

**Comment by okbob** [comment]
please, try to run `configure` first. Probably you has not installed unicode ncurses - `ncursesw` library. On debian this library is in separate package  https://packages.debian.org/jessie/libncursesw5-dev or https://packages.debian.org/sid/libncurses6
