### ISSUE TITLE
Use as popup-menu (context-menu)

### ISSUE THREAD

**Issue by GitMensch** [okbob/ncurses-st-menu#7]
Is it possible to use ncurses-st-menu as context menu (a panel including the "normal" menu definition horizontally) already?

If not: please consider this feature request.

**Comment by okbob** [comment]
I am sorry I don't understand to question. I am messy when you talk about context menu and about horizontal definition. What do you mean? Pupup menu are vertical. 

Vertical menu are allowed. I didn't tested it well, but you can look on st_menu_new function. Some months ago I wrote simple demo - it is attached now - see simple2

**Comment by GitMensch** [comment]
... you're completely correct, always those late-night comments ;-) this was about a popup.

It is good that you've added the demo, can you please also add a screenshot of it (I'm currently not on my dev machine...) and possibly also start each of the demo sources with a short comment block what this demo is about?

I guess this issue can be closed soon :-)

**Comment by okbob** [comment]
![Snímek z 2020-02-26 07-40-09](https://user-images.githubusercontent.com/546675/75318680-40cad100-586b-11ea-994f-399afbec3abd.png)

**Comment by GitMensch** [comment]
Thank you for the screenshot.

I assume we can have defined shortcuts, dividers, sub-menus and all other stuff in there, too.

If not we can track those extensions of the popup here.

If yes:
* please create a demo+screenshot showing this and add it to the repo + README
* please close this issue

[please still consider adding the comment block on each of the the demo's header what the demo is about]

**Comment by okbob** [comment]
b05ed827b06f258b3f828f063a188a74a565a580

**Comment by GitMensch** [comment]
thank you for the updated sample (until told otherwise I'll likely ask about an additional screenshot for the popup menu and the comment block on the samples ; - )
