### ISSUE TITLE
remove autogen + configure-generated files

### ISSUE THREAD

**Issue by GitMensch** [okbob/ncurses-st-menu#8]
* configure (generated from configure.ac when running autogen.sh and heavily different depending on the actual version of the installed tools, so very likely to get conflicts when generated with a different version)
* st_menu.pc (generated during configure from st_menu.pc.in)
* config.make (generated during configure from config.make.in)

When looking at @tysenmoore-xse's repo we also see that as long as the generated files are in it happens that those are adjusted and committed, instead of the "sources", which is another reason to remove them.

Together with the deletion I suggest to add those files to git ignore.

**Comment by tysenmoore-xse** [comment]
@GitMensch 
In my latest PR I removed the configure file as well and added it to the cleanconfig and .gitignore.  I missed it in my previous changes.  My PR already had the config.make and st_menu.pc.

**Comment by GitMensch** [comment]
Hm, the two extra files are not part of your latest commit, it only has a delete on the configure script (those two files are part of gitignore which may be a reason for some issues).

@okbob I suggest to get rid of those three files, also adding them to gitignore where missing - and additional *consider* to remove aclocal.m4 (from repo, added to gitignore), too; as it also gets in during autoconf.

**Comment by okbob** [comment]
"configure" should to stay. No every body has installed autoconf. 

Should be cleaned now - af4a96f4da2c14ee6ab582dae3438a04be109844 b7ac47ae5ba6f7547656fb49e58c16cf32e5e9c7

**Comment by GitMensch** [comment]
@okbob actually I suggest to have the repo *only* contain everything that cannot be generated. As soon as this is in sight I'd suggest (and do the work + PR if accepted) to use a CI build to auto-generate a tarball which contains everything needed.
To get an idea: https://sourceforge.net/p/open-cobol/code/HEAD/tree/branches/gnucobol-3.x/ + https://ci.appveyor.com/project/GitMensch/gnucobol-3-x :-)

**Comment by okbob** [comment]
st 26. 2. 2020 v 19:07 odesílatel Simon Sobisch <notifications@github.com>
napsal:

> @okbob <https://github.com/okbob> actually I suggest to have the repo
> *only* contain everything that cannot be generated. As soon as this is in
> sight I'd suggest (and do the work + PR if accepted) to use a CI build to
> auto-generate a tarball which contains everything needed.
> To get an idea:
> https://sourceforge.net/p/open-cobol/code/HEAD/tree/branches/gnucobol-3.x/
> + https://ci.appveyor.com/project/GitMensch/gnucobol-3-x :-)
>
I understand, but for some people can be more easy to have "configure"
file. Same rule has postgres.
